# Generated by Django 4.2.1 on 2025-06-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0004_dataupload_pagecontent_siteconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
        ),
        migrations.DeleteModel(
            name='DataUpload',
        ),
        migrations.DeleteModel(
            name='PageContent',
        ),
        migrations.DeleteModel(
            name='SiteConfiguration',
        ),
        migrations.DeleteModel(
            name='StatisticalData',
        ),
        migrations.DeleteModel(
            name='VacancyData',
        ),
    ]
